"""
NYC Neighborhood data with characteristics
In production, this would come from a database
"""

def get_nyc_neighborhoods():
    """
    Returns list of NYC neighborhoods with their characteristics
    """
    neighborhoods = [
        # Manhattan
        {
            'name': 'Upper East Side',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Upper East Side',
            'street_name': 'Park Avenue',
            'lat': 40.7736,
            'lng': -73.9566,
            'walkability': 95,
            'food_score': 9,
            'nightlife_score': 6,
            'transit_score': 10,
            'parks_score': 9,
            'diversity_score': 6,
            'safety_score': 9,
            'primary_demographic': 'professionals',
            'vibe': 'upscale and quiet',
            'food_density': 'Very High',
            'sentiment': 8.2
        },
        {
            'name': 'Greenwich Village',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Greenwich Village',
            'street_name': 'Bleecker Street',
            'lat': 40.7336,
            'lng': -74.0027,
            'walkability': 98,
            'food_score': 10,
            'nightlife_score': 9,
            'transit_score': 10,
            'parks_score': 7,
            'diversity_score': 8,
            'safety_score': 8,
            'primary_demographic': 'young professionals',
            'vibe': 'vibrant and artsy',
            'food_density': 'Very High',
            'sentiment': 9.1
        },
        {
            'name': 'Harlem',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Harlem',
            'street_name': '125th Street',
            'lat': 40.8116,
            'lng': -73.9465,
            'walkability': 90,
            'food_score': 8,
            'nightlife_score': 7,
            'transit_score': 9,
            'parks_score': 6,
            'diversity_score': 9,
            'safety_score': 6,
            'primary_demographic': 'families',
            'vibe': 'cultural and historic',
            'food_density': 'High',
            'sentiment': 7.8
        },
        {
            'name': 'Financial District',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Financial District',
            'street_name': 'Wall Street',
            'lat': 40.7074,
            'lng': -74.0113,
            'walkability': 92,
            'food_score': 7,
            'nightlife_score': 4,
            'transit_score': 10,
            'parks_score': 5,
            'diversity_score': 7,
            'safety_score': 9,
            'primary_demographic': 'professionals',
            'vibe': 'business-focused',
            'food_density': 'High',
            'sentiment': 7.0
        },
        # Brooklyn
        {
            'name': 'Williamsburg',
            'admin_area': 'Brooklyn',
            'locality': 'New York',
            'sublocality': 'Williamsburg',
            'street_name': 'Bedford Avenue',
            'lat': 40.7081,
            'lng': -73.9571,
            'walkability': 95,
            'food_score': 9,
            'nightlife_score': 9,
            'transit_score': 8,
            'parks_score': 7,
            'diversity_score': 8,
            'safety_score': 7,
            'primary_demographic': 'young professionals',
            'vibe': 'hipster and trendy',
            'food_density': 'Very High',
            'sentiment': 8.5
        },
        {
            'name': 'Park Slope',
            'admin_area': 'Brooklyn',
            'locality': 'New York',
            'sublocality': 'Park Slope',
            'street_name': '7th Avenue',
            'lat': 40.6710,
            'lng': -73.9796,
            'walkability': 93,
            'food_score': 8,
            'nightlife_score': 5,
            'transit_score': 8,
            'parks_score': 10,
            'diversity_score': 7,
            'safety_score': 9,
            'primary_demographic': 'families',
            'vibe': 'family-friendly',
            'food_density': 'High',
            'sentiment': 8.8
        },
        {
            'name': 'DUMBO',
            'admin_area': 'Brooklyn',
            'locality': 'New York',
            'sublocality': 'DUMBO',
            'street_name': 'Front Street',
            'lat': 40.7033,
            'lng': -73.9888,
            'walkability': 88,
            'food_score': 7,
            'nightlife_score': 6,
            'transit_score': 9,
            'parks_score': 8,
            'diversity_score': 6,
            'safety_score': 8,
            'primary_demographic': 'young professionals',
            'vibe': 'modern and scenic',
            'food_density': 'Medium',
            'sentiment': 8.3
        },
        # Queens
        {
            'name': 'Astoria',
            'admin_area': 'Queens',
            'locality': 'New York',
            'sublocality': 'Astoria',
            'street_name': 'Steinway Street',
            'lat': 40.7644,
            'lng': -73.9235,
            'walkability': 85,
            'food_score': 9,
            'nightlife_score': 7,
            'transit_score': 8,
            'parks_score': 6,
            'diversity_score': 10,
            'safety_score': 7,
            'primary_demographic': 'mixed',
            'vibe': 'diverse and affordable',
            'food_density': 'Very High',
            'sentiment': 8.4
        },
        {
            'name': 'Long Island City',
            'admin_area': 'Queens',
            'locality': 'New York',
            'sublocality': 'Long Island City',
            'street_name': 'Jackson Avenue',
            'lat': 40.7447,
            'lng': -73.9485,
            'walkability': 82,
            'food_score': 7,
            'nightlife_score': 6,
            'transit_score': 9,
            'parks_score': 7,
            'diversity_score': 8,
            'safety_score': 7,
            'primary_demographic': 'young professionals',
            'vibe': 'up-and-coming',
            'food_density': 'Medium',
            'sentiment': 7.9
        },
        {
            'name': 'Flushing',
            'admin_area': 'Queens',
            'locality': 'New York',
            'sublocality': 'Flushing',
            'street_name': 'Main Street',
            'lat': 40.7673,
            'lng': -73.8333,
            'walkability': 78,
            'food_score': 10,
            'nightlife_score': 6,
            'transit_score': 7,
            'parks_score': 6,
            'diversity_score': 10,
            'safety_score': 8,
            'primary_demographic': 'families',
            'vibe': 'multicultural hub',
            'food_density': 'Very High',
            'sentiment': 8.0
        },
        # Bronx
        {
            'name': 'Riverdale',
            'admin_area': 'Bronx',
            'locality': 'New York',
            'sublocality': 'Riverdale',
            'street_name': 'Riverdale Avenue',
            'lat': 40.8908,
            'lng': -73.9057,
            'walkability': 65,
            'food_score': 6,
            'nightlife_score': 3,
            'transit_score': 6,
            'parks_score': 9,
            'diversity_score': 7,
            'safety_score': 9,
            'primary_demographic': 'families',
            'vibe': 'suburban and quiet',
            'food_density': 'Medium',
            'sentiment': 8.1
        },
        {
            'name': 'Fordham',
            'admin_area': 'Bronx',
            'locality': 'New York',
            'sublocality': 'Fordham',
            'street_name': 'Fordham Road',
            'lat': 40.8623,
            'lng': -73.8989,
            'walkability': 80,
            'food_score': 7,
            'nightlife_score': 5,
            'transit_score': 8,
            'parks_score': 5,
            'diversity_score': 9,
            'safety_score': 6,
            'primary_demographic': 'students',
            'vibe': 'college town feel',
            'food_density': 'High',
            'sentiment': 7.3
        },
        # Staten Island
        {
            'name': 'St. George',
            'admin_area': 'Staten Island',
            'locality': 'New York',
            'sublocality': 'St. George',
            'street_name': 'Bay Street',
            'lat': 40.6437,
            'lng': -74.0773,
            'walkability': 70,
            'food_score': 6,
            'nightlife_score': 4,
            'transit_score': 7,
            'parks_score': 8,
            'diversity_score': 7,
            'safety_score': 7,
            'primary_demographic': 'families',
            'vibe': 'waterfront community',
            'food_density': 'Medium',
            'sentiment': 7.5
        }
    ]

    return neighborhoods
