"""
NYC Neighborhood data with characteristics
In production, this would come from a database
"""

def get_nyc_neighborhoods():
    """
    Returns list of NYC neighborhoods with their characteristics
    """
    neighborhoods = [
        # ==================== MANHATTAN ====================
        {
            'name': 'Upper East Side',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Upper East Side',
            'street_name': 'Park Avenue',
            'lat': 40.7736,
            'lng': -73.9566,
            'walkability': 95,
            'food_score': 9,
            'nightlife_score': 6,
            'transit_score': 10,
            'parks_score': 9,
            'diversity_score': 6,
            'safety_score': 9,
            'primary_demographic': 'professionals',
            'vibe': 'upscale and quiet',
            'food_density': 'Very High',
            'sentiment': 8.2
        },
        {
            'name': 'Upper West Side',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Upper West Side',
            'street_name': 'Broadway',
            'lat': 40.7870,
            'lng': -73.9754,
            'walkability': 96,
            'food_score': 9,
            'nightlife_score': 6,
            'transit_score': 10,
            'parks_score': 10,
            'diversity_score': 7,
            'safety_score': 9,
            'primary_demographic': 'families',
            'vibe': 'cultured and residential',
            'food_density': 'Very High',
            'sentiment': 8.6
        },
        {
            'name': 'Greenwich Village',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Greenwich Village',
            'street_name': 'Bleecker Street',
            'lat': 40.7336,
            'lng': -74.0027,
            'walkability': 98,
            'food_score': 10,
            'nightlife_score': 9,
            'transit_score': 10,
            'parks_score': 7,
            'diversity_score': 8,
            'safety_score': 8,
            'primary_demographic': 'young professionals',
            'vibe': 'vibrant and artsy',
            'food_density': 'Very High',
            'sentiment': 9.1
        },
        {
            'name': 'East Village',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'East Village',
            'street_name': 'Avenue A',
            'lat': 40.7264,
            'lng': -73.9818,
            'walkability': 97,
            'food_score': 10,
            'nightlife_score': 10,
            'transit_score': 9,
            'parks_score': 6,
            'diversity_score': 9,
            'safety_score': 7,
            'primary_demographic': 'young professionals',
            'vibe': 'edgy and eclectic',
            'food_density': 'Very High',
            'sentiment': 8.7
        },
        {
            'name': 'SoHo',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'SoHo',
            'street_name': 'Broadway',
            'lat': 40.7233,
            'lng': -74.0030,
            'walkability': 98,
            'food_score': 9,
            'nightlife_score': 8,
            'transit_score': 10,
            'parks_score': 4,
            'diversity_score': 7,
            'safety_score': 8,
            'primary_demographic': 'young professionals',
            'vibe': 'fashionable and artistic',
            'food_density': 'Very High',
            'sentiment': 8.9
        },
        {
            'name': 'Tribeca',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Tribeca',
            'street_name': 'Hudson Street',
            'lat': 40.7163,
            'lng': -74.0086,
            'walkability': 95,
            'food_score': 9,
            'nightlife_score': 7,
            'transit_score': 9,
            'parks_score': 6,
            'diversity_score': 6,
            'safety_score': 9,
            'primary_demographic': 'families',
            'vibe': 'upscale and family-oriented',
            'food_density': 'Very High',
            'sentiment': 8.8
        },
        {
            'name': 'Chelsea',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Chelsea',
            'street_name': '8th Avenue',
            'lat': 40.7465,
            'lng': -74.0014,
            'walkability': 96,
            'food_score': 9,
            'nightlife_score': 9,
            'transit_score': 10,
            'parks_score': 7,
            'diversity_score': 9,
            'safety_score': 8,
            'primary_demographic': 'young professionals',
            'vibe': 'artsy and LGBTQ-friendly',
            'food_density': 'Very High',
            'sentiment': 8.8
        },
        {
            'name': 'Harlem',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Harlem',
            'street_name': '125th Street',
            'lat': 40.8116,
            'lng': -73.9465,
            'walkability': 90,
            'food_score': 8,
            'nightlife_score': 7,
            'transit_score': 9,
            'parks_score': 6,
            'diversity_score': 9,
            'safety_score': 6,
            'primary_demographic': 'families',
            'vibe': 'cultural and historic',
            'food_density': 'High',
            'sentiment': 7.8
        },
        {
            'name': 'Financial District',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Financial District',
            'street_name': 'Wall Street',
            'lat': 40.7074,
            'lng': -74.0113,
            'walkability': 92,
            'food_score': 7,
            'nightlife_score': 4,
            'transit_score': 10,
            'parks_score': 5,
            'diversity_score': 7,
            'safety_score': 9,
            'primary_demographic': 'professionals',
            'vibe': 'business-focused',
            'food_density': 'High',
            'sentiment': 7.0
        },
        {
            'name': 'Battery Park City',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Battery Park City',
            'street_name': 'West Street',
            'lat': 40.7131,
            'lng': -74.0169,
            'walkability': 93,
            'food_score': 7,
            'nightlife_score': 4,
            'transit_score': 9,
            'parks_score': 10,
            'diversity_score': 6,
            'safety_score': 10,
            'primary_demographic': 'families',
            'vibe': 'planned and peaceful',
            'food_density': 'Medium',
            'sentiment': 8.4
        },
        {
            'name': 'Hell\'s Kitchen',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Hell\'s Kitchen',
            'street_name': '9th Avenue',
            'lat': 40.7638,
            'lng': -73.9918,
            'walkability': 97,
            'food_score': 10,
            'nightlife_score': 8,
            'transit_score': 10,
            'parks_score': 5,
            'diversity_score': 8,
            'safety_score': 7,
            'primary_demographic': 'young professionals',
            'vibe': 'diverse and bustling',
            'food_density': 'Very High',
            'sentiment': 8.3
        },
        {
            'name': 'Midtown',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Midtown',
            'street_name': '5th Avenue',
            'lat': 40.7549,
            'lng': -73.9840,
            'walkability': 98,
            'food_score': 8,
            'nightlife_score': 7,
            'transit_score': 10,
            'parks_score': 5,
            'diversity_score': 8,
            'safety_score': 8,
            'primary_demographic': 'professionals',
            'vibe': 'touristy and commercial',
            'food_density': 'Very High',
            'sentiment': 7.2
        },
        {
            'name': 'Murray Hill',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Murray Hill',
            'street_name': 'Lexington Avenue',
            'lat': 40.7478,
            'lng': -73.9753,
            'walkability': 94,
            'food_score': 8,
            'nightlife_score': 7,
            'transit_score': 10,
            'parks_score': 5,
            'diversity_score': 7,
            'safety_score': 8,
            'primary_demographic': 'young professionals',
            'vibe': 'residential and convenient',
            'food_density': 'High',
            'sentiment': 7.9
        },
        {
            'name': 'Gramercy',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Gramercy',
            'street_name': '3rd Avenue',
            'lat': 40.7368,
            'lng': -73.9841,
            'walkability': 96,
            'food_score': 9,
            'nightlife_score': 7,
            'transit_score': 10,
            'parks_score': 8,
            'diversity_score': 7,
            'safety_score': 9,
            'primary_demographic': 'professionals',
            'vibe': 'historic and charming',
            'food_density': 'Very High',
            'sentiment': 8.7
        },
        {
            'name': 'Union Square',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Union Square',
            'street_name': '14th Street',
            'lat': 40.7359,
            'lng': -73.9911,
            'walkability': 99,
            'food_score': 9,
            'nightlife_score': 8,
            'transit_score': 10,
            'parks_score': 7,
            'diversity_score': 9,
            'safety_score': 7,
            'primary_demographic': 'mixed',
            'vibe': 'energetic and central',
            'food_density': 'Very High',
            'sentiment': 8.5
        },
        {
            'name': 'Lower East Side',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Lower East Side',
            'street_name': 'Orchard Street',
            'lat': 40.7153,
            'lng': -73.9877,
            'walkability': 95,
            'food_score': 10,
            'nightlife_score': 10,
            'transit_score': 9,
            'parks_score': 5,
            'diversity_score': 9,
            'safety_score': 6,
            'primary_demographic': 'young professionals',
            'vibe': 'trendy and nightlife-heavy',
            'food_density': 'Very High',
            'sentiment': 8.4
        },
        {
            'name': 'Chinatown',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Chinatown',
            'street_name': 'Canal Street',
            'lat': 40.7157,
            'lng': -73.9970,
            'walkability': 94,
            'food_score': 10,
            'nightlife_score': 5,
            'transit_score': 9,
            'parks_score': 3,
            'diversity_score': 10,
            'safety_score': 7,
            'primary_demographic': 'mixed',
            'vibe': 'authentic and crowded',
            'food_density': 'Very High',
            'sentiment': 7.6
        },
        {
            'name': 'Little Italy',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Little Italy',
            'street_name': 'Mulberry Street',
            'lat': 40.7194,
            'lng': -73.9977,
            'walkability': 95,
            'food_score': 9,
            'nightlife_score': 6,
            'transit_score': 9,
            'parks_score': 4,
            'diversity_score': 8,
            'safety_score': 7,
            'primary_demographic': 'mixed',
            'vibe': 'historic and touristy',
            'food_density': 'Very High',
            'sentiment': 7.8
        },
        {
            'name': 'NoHo',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'NoHo',
            'street_name': 'Lafayette Street',
            'lat': 40.7270,
            'lng': -73.9943,
            'walkability': 97,
            'food_score': 9,
            'nightlife_score': 8,
            'transit_score': 10,
            'parks_score': 5,
            'diversity_score': 7,
            'safety_score': 8,
            'primary_demographic': 'young professionals',
            'vibe': 'artistic and upscale',
            'food_density': 'Very High',
            'sentiment': 8.6
        },
        {
            'name': 'Flatiron',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Flatiron',
            'street_name': 'Broadway',
            'lat': 40.7410,
            'lng': -73.9896,
            'walkability': 98,
            'food_score': 9,
            'nightlife_score': 7,
            'transit_score': 10,
            'parks_score': 6,
            'diversity_score': 7,
            'safety_score': 8,
            'primary_demographic': 'professionals',
            'vibe': 'tech hub and modern',
            'food_density': 'Very High',
            'sentiment': 8.4
        },
        {
            'name': 'Washington Heights',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Washington Heights',
            'street_name': 'Broadway',
            'lat': 40.8498,
            'lng': -73.9366,
            'walkability': 88,
            'food_score': 8,
            'nightlife_score': 6,
            'transit_score': 8,
            'parks_score': 7,
            'diversity_score': 10,
            'safety_score': 6,
            'primary_demographic': 'families',
            'vibe': 'diverse and affordable',
            'food_density': 'High',
            'sentiment': 7.7
        },
        {
            'name': 'Inwood',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Inwood',
            'street_name': 'Dyckman Street',
            'lat': 40.8677,
            'lng': -73.9212,
            'walkability': 85,
            'food_score': 7,
            'nightlife_score': 5,
            'transit_score': 7,
            'parks_score': 9,
            'diversity_score': 9,
            'safety_score': 6,
            'primary_demographic': 'families',
            'vibe': 'quiet and green',
            'food_density': 'Medium',
            'sentiment': 7.6
        },
        {
            'name': 'Morningside Heights',
            'admin_area': 'Manhattan',
            'locality': 'New York',
            'sublocality': 'Morningside Heights',
            'street_name': 'Broadway',
            'lat': 40.8102,
            'lng': -73.9627,
            'walkability': 91,
            'food_score': 7,
            'nightlife_score': 6,
            'transit_score': 9,
            'parks_score': 8,
            'diversity_score': 8,
            'safety_score': 7,
            'primary_demographic': 'students',
            'vibe': 'academic and calm',
            'food_density': 'High',
            'sentiment': 7.9
        },

        # ==================== BROOKLYN ====================
        {
            'name': 'Williamsburg',
            'admin_area': 'Brooklyn',
            'locality': 'New York',
            'sublocality': 'Williamsburg',
            'street_name': 'Bedford Avenue',
            'lat': 40.7081,
            'lng': -73.9571,
            'walkability': 95,
            'food_score': 9,
            'nightlife_score': 9,
            'transit_score': 8,
            'parks_score': 7,
            'diversity_score': 8,
            'safety_score': 7,
            'primary_demographic': 'young professionals',
            'vibe': 'hipster and trendy',
            'food_density': 'Very High',
            'sentiment': 8.5
        },
        {
            'name': 'Park Slope',
            'admin_area': 'Brooklyn',
            'locality': 'New York',
            'sublocality': 'Park Slope',
            'street_name': '7th Avenue',
            'lat': 40.6710,
            'lng': -73.9796,
            'walkability': 93,
            'food_score': 8,
            'nightlife_score': 5,
            'transit_score': 8,
            'parks_score': 10,
            'diversity_score': 7,
            'safety_score': 9,
            'primary_demographic': 'families',
            'vibe': 'family-friendly',
            'food_density': 'High',
            'sentiment': 8.8
        },
        {
            'name': 'DUMBO',
            'admin_area': 'Brooklyn',
            'locality': 'New York',
            'sublocality': 'DUMBO',
            'street_name': 'Front Street',
            'lat': 40.7033,
            'lng': -73.9888,
            'walkability': 88,
            'food_score': 7,
            'nightlife_score': 6,
            'transit_score': 9,
            'parks_score': 8,
            'diversity_score': 6,
            'safety_score': 8,
            'primary_demographic': 'young professionals',
            'vibe': 'modern and scenic',
            'food_density': 'Medium',
            'sentiment': 8.3
        },
        {
            'name': 'Brooklyn Heights',
            'admin_area': 'Brooklyn',
            'locality': 'New York',
            'sublocality': 'Brooklyn Heights',
            'street_name': 'Montague Street',
            'lat': 40.6958,
            'lng': -73.9936,
            'walkability': 94,
            'food_score': 8,
            'nightlife_score': 5,
            'transit_score': 9,
            'parks_score': 9,
            'diversity_score': 6,
            'safety_score': 9,
            'primary_demographic': 'families',
            'vibe': 'historic and upscale',
            'food_density': 'High',
            'sentiment': 8.9
        },
        {
            'name': 'Bushwick',
            'admin_area': 'Brooklyn',
            'locality': 'New York',
            'sublocality': 'Bushwick',
            'street_name': 'Knickerbocker Avenue',
            'lat': 40.6942,
            'lng': -73.9226,
            'walkability': 87,
            'food_score': 8,
            'nightlife_score': 9,
            'transit_score': 7,
            'parks_score': 5,
            'diversity_score': 9,
            'safety_score': 6,
            'primary_demographic': 'young professionals',
            'vibe': 'artsy and emerging',
            'food_density': 'High',
            'sentiment': 7.9
        },
        {
            'name': 'Greenpoint',
            'admin_area': 'Brooklyn',
            'locality': 'New York',
            'sublocality': 'Greenpoint',
            'street_name': 'Manhattan Avenue',
            'lat': 40.7298,
            'lng': -73.9524,
            'walkability': 90,
            'food_score': 8,
            'nightlife_score': 7,
            'transit_score': 7,
            'parks_score': 6,
            'diversity_score': 8,
            'safety_score': 7,
            'primary_demographic': 'young professionals',
            'vibe': 'Polish heritage meets hipster',
            'food_density': 'High',
            'sentiment': 8.2
        },
        {
            'name': 'Red Hook',
            'admin_area': 'Brooklyn',
            'locality': 'New York',
            'sublocality': 'Red Hook',
            'street_name': 'Van Brunt Street',
            'lat': 40.6755,
            'lng': -74.0121,
            'walkability': 72,
            'food_score': 7,
            'nightlife_score': 5,
            'transit_score': 4,
            'parks_score': 8,
            'diversity_score': 7,
            'safety_score': 6,
            'primary_demographic': 'mixed',
            'vibe': 'waterfront and industrial',
            'food_density': 'Medium',
            'sentiment': 7.8
        },
        {
            'name': 'Carroll Gardens',
            'admin_area': 'Brooklyn',
            'locality': 'New York',
            'sublocality': 'Carroll Gardens',
            'street_name': 'Court Street',
            'lat': 40.6805,
            'lng': -73.9995,
            'walkability': 92,
            'food_score': 9,
            'nightlife_score': 6,
            'transit_score': 8,
            'parks_score': 7,
            'diversity_score': 7,
            'safety_score': 9,
            'primary_demographic': 'families',
            'vibe': 'charming and residential',
            'food_density': 'Very High',
            'sentiment': 8.7
        },
        {
            'name': 'Cobble Hill',
            'admin_area': 'Brooklyn',
            'locality': 'New York',
            'sublocality': 'Cobble Hill',
            'street_name': 'Court Street',
            'lat': 40.6881,
            'lng': -73.9960,
            'walkability': 93,
            'food_score': 8,
            'nightlife_score': 6,
            'transit_score': 8,
            'parks_score': 7,
            'diversity_score': 7,
            'safety_score': 9,
            'primary_demographic': 'families',
            'vibe': 'quiet and quaint',
            'food_density': 'High',
            'sentiment': 8.6
        },
        {
            'name': 'Fort Greene',
            'admin_area': 'Brooklyn',
            'locality': 'New York',
            'sublocality': 'Fort Greene',
            'street_name': 'Myrtle Avenue',
            'lat': 40.6913,
            'lng': -73.9742,
            'walkability': 91,
            'food_score': 8,
            'nightlife_score': 7,
            'transit_score': 9,
            'parks_score': 9,
            'diversity_score': 9,
            'safety_score': 7,
            'primary_demographic': 'mixed',
            'vibe': 'cultural and artistic',
            'food_density': 'High',
            'sentiment': 8.5
        },
        {
            'name': 'Bed-Stuy',
            'admin_area': 'Brooklyn',
            'locality': 'New York',
            'sublocality': 'Bedford-Stuyvesant',
            'street_name': 'Fulton Street',
            'lat': 40.6872,
            'lng': -73.9418,
            'walkability': 86,
            'food_score': 7,
            'nightlife_score': 6,
            'transit_score': 8,
            'parks_score': 6,
            'diversity_score': 9,
            'safety_score': 6,
            'primary_demographic': 'families',
            'vibe': 'historic brownstones',
            'food_density': 'High',
            'sentiment': 7.7
        },
        {
            'name': 'Crown Heights',
            'admin_area': 'Brooklyn',
            'locality': 'New York',
            'sublocality': 'Crown Heights',
            'street_name': 'Nostrand Avenue',
            'lat': 40.6694,
            'lng': -73.9422,
            'walkability': 87,
            'food_score': 8,
            'nightlife_score': 6,
            'transit_score': 8,
            'parks_score': 7,
            'diversity_score': 10,
            'safety_score': 6,
            'primary_demographic': 'families',
            'vibe': 'diverse and vibrant',
            'food_density': 'High',
            'sentiment': 7.8
        },
        {
            'name': 'Prospect Heights',
            'admin_area': 'Brooklyn',
            'locality': 'New York',
            'sublocality': 'Prospect Heights',
            'street_name': 'Flatbush Avenue',
            'lat': 40.6775,
            'lng': -73.9692,
            'walkability': 90,
            'food_score': 8,
            'nightlife_score': 6,
            'transit_score': 9,
            'parks_score': 9,
            'diversity_score': 8,
            'safety_score': 8,
            'primary_demographic': 'young professionals',
            'vibe': 'trendy and cultural',
            'food_density': 'High',
            'sentiment': 8.4
        },
        {
            'name': 'Sunset Park',
            'admin_area': 'Brooklyn',
            'locality': 'New York',
            'sublocality': 'Sunset Park',
            'street_name': '8th Avenue',
            'lat': 40.6454,
            'lng': -74.0055,
            'walkability': 82,
            'food_score': 9,
            'nightlife_score': 5,
            'transit_score': 7,
            'parks_score': 8,
            'diversity_score': 10,
            'safety_score': 6,
            'primary_demographic': 'families',
            'vibe': 'multicultural and affordable',
            'food_density': 'Very High',
            'sentiment': 7.6
        },
        {
            'name': 'Bay Ridge',
            'admin_area': 'Brooklyn',
            'locality': 'New York',
            'sublocality': 'Bay Ridge',
            'street_name': '3rd Avenue',
            'lat': 40.6260,
            'lng': -74.0307,
            'walkability': 80,
            'food_score': 8,
            'nightlife_score': 5,
            'transit_score': 6,
            'parks_score': 7,
            'diversity_score': 8,
            'safety_score': 8,
            'primary_demographic': 'families',
            'vibe': 'suburban feel',
            'food_density': 'High',
            'sentiment': 7.9
        },
        {
            'name': 'Bensonhurst',
            'admin_area': 'Brooklyn',
            'locality': 'New York',
            'sublocality': 'Bensonhurst',
            'street_name': '86th Street',
            'lat': 40.6016,
            'lng': -73.9941,
            'walkability': 78,
            'food_score': 8,
            'nightlife_score': 4,
            'transit_score': 6,
            'parks_score': 6,
            'diversity_score': 9,
            'safety_score': 7,
            'primary_demographic': 'families',
            'vibe': 'tight-knit community',
            'food_density': 'High',
            'sentiment': 7.5
        },
        {
            'name': 'Sheepshead Bay',
            'admin_area': 'Brooklyn',
            'locality': 'New York',
            'sublocality': 'Sheepshead Bay',
            'street_name': 'Emmons Avenue',
            'lat': 40.5873,
            'lng': -73.9442,
            'walkability': 75,
            'food_score': 7,
            'nightlife_score': 4,
            'transit_score': 6,
            'parks_score': 7,
            'diversity_score': 8,
            'safety_score': 7,
            'primary_demographic': 'families',
            'vibe': 'waterfront community',
            'food_density': 'Medium',
            'sentiment': 7.4
        },
        {
            'name': 'Brighton Beach',
            'admin_area': 'Brooklyn',
            'locality': 'New York',
            'sublocality': 'Brighton Beach',
            'street_name': 'Brighton Beach Avenue',
            'lat': 40.5776,
            'lng': -73.9609,
            'walkability': 82,
            'food_score': 9,
            'nightlife_score': 5,
            'transit_score': 7,
            'parks_score': 8,
            'diversity_score': 9,
            'safety_score': 6,
            'primary_demographic': 'families',
            'vibe': 'Russian community and beach',
            'food_density': 'Very High',
            'sentiment': 7.7
        },
        {
            'name': 'Coney Island',
            'admin_area': 'Brooklyn',
            'locality': 'New York',
            'sublocality': 'Coney Island',
            'street_name': 'Surf Avenue',
            'lat': 40.5755,
            'lng': -73.9707,
            'walkability': 76,
            'food_score': 6,
            'nightlife_score': 6,
            'transit_score': 6,
            'parks_score': 9,
            'diversity_score': 8,
            'safety_score': 5,
            'primary_demographic': 'mixed',
            'vibe': 'iconic and beachy',
            'food_density': 'Medium',
            'sentiment': 7.1
        },

        # ==================== QUEENS ====================
        {
            'name': 'Astoria',
            'admin_area': 'Queens',
            'locality': 'New York',
            'sublocality': 'Astoria',
            'street_name': 'Steinway Street',
            'lat': 40.7644,
            'lng': -73.9235,
            'walkability': 85,
            'food_score': 9,
            'nightlife_score': 7,
            'transit_score': 8,
            'parks_score': 6,
            'diversity_score': 10,
            'safety_score': 7,
            'primary_demographic': 'mixed',
            'vibe': 'diverse and affordable',
            'food_density': 'Very High',
            'sentiment': 8.4
        },
        {
            'name': 'Long Island City',
            'admin_area': 'Queens',
            'locality': 'New York',
            'sublocality': 'Long Island City',
            'street_name': 'Jackson Avenue',
            'lat': 40.7447,
            'lng': -73.9485,
            'walkability': 82,
            'food_score': 7,
            'nightlife_score': 6,
            'transit_score': 9,
            'parks_score': 7,
            'diversity_score': 8,
            'safety_score': 7,
            'primary_demographic': 'young professionals',
            'vibe': 'up-and-coming',
            'food_density': 'Medium',
            'sentiment': 7.9
        },
        {
            'name': 'Flushing',
            'admin_area': 'Queens',
            'locality': 'New York',
            'sublocality': 'Flushing',
            'street_name': 'Main Street',
            'lat': 40.7673,
            'lng': -73.8333,
            'walkability': 78,
            'food_score': 10,
            'nightlife_score': 6,
            'transit_score': 7,
            'parks_score': 6,
            'diversity_score': 10,
            'safety_score': 8,
            'primary_demographic': 'families',
            'vibe': 'multicultural hub',
            'food_density': 'Very High',
            'sentiment': 8.0
        },
        {
            'name': 'Forest Hills',
            'admin_area': 'Queens',
            'locality': 'New York',
            'sublocality': 'Forest Hills',
            'street_name': 'Austin Street',
            'lat': 40.7185,
            'lng': -73.8448,
            'walkability': 80,
            'food_score': 8,
            'nightlife_score': 5,
            'transit_score': 8,
            'parks_score': 8,
            'diversity_score': 8,
            'safety_score': 9,
            'primary_demographic': 'families',
            'vibe': 'suburban and leafy',
            'food_density': 'High',
            'sentiment': 8.3
        },
        {
            'name': 'Sunnyside',
            'admin_area': 'Queens',
            'locality': 'New York',
            'sublocality': 'Sunnyside',
            'street_name': 'Queens Boulevard',
            'lat': 40.7432,
            'lng': -73.9196,
            'walkability': 83,
            'food_score': 8,
            'nightlife_score': 6,
            'transit_score': 9,
            'parks_score': 6,
            'diversity_score': 9,
            'safety_score': 7,
            'primary_demographic': 'families',
            'vibe': 'quiet gardens community',
            'food_density': 'High',
            'sentiment': 8.1
        },
        {
            'name': 'Woodside',
            'admin_area': 'Queens',
            'locality': 'New York',
            'sublocality': 'Woodside',
            'street_name': 'Roosevelt Avenue',
            'lat': 40.7456,
            'lng': -73.9026,
            'walkability': 81,
            'food_score': 8,
            'nightlife_score': 6,
            'transit_score': 8,
            'parks_score': 5,
            'diversity_score': 10,
            'safety_score': 7,
            'primary_demographic': 'families',
            'vibe': 'diverse and working-class',
            'food_density': 'High',
            'sentiment': 7.7
        },
        {
            'name': 'Jackson Heights',
            'admin_area': 'Queens',
            'locality': 'New York',
            'sublocality': 'Jackson Heights',
            'street_name': '37th Avenue',
            'lat': 40.7557,
            'lng': -73.8831,
            'walkability': 84,
            'food_score': 10,
            'nightlife_score': 6,
            'transit_score': 8,
            'parks_score': 5,
            'diversity_score': 10,
            'safety_score': 6,
            'primary_demographic': 'families',
            'vibe': 'incredibly diverse',
            'food_density': 'Very High',
            'sentiment': 8.0
        },
        {
            'name': 'Elmhurst',
            'admin_area': 'Queens',
            'locality': 'New York',
            'sublocality': 'Elmhurst',
            'street_name': 'Broadway',
            'lat': 40.7361,
            'lng': -73.8778,
            'walkability': 80,
            'food_score': 9,
            'nightlife_score': 5,
            'transit_score': 8,
            'parks_score': 6,
            'diversity_score': 10,
            'safety_score': 7,
            'primary_demographic': 'families',
            'vibe': 'multicultural center',
            'food_density': 'Very High',
            'sentiment': 7.9
        },
        {
            'name': 'Rego Park',
            'admin_area': 'Queens',
            'locality': 'New York',
            'sublocality': 'Rego Park',
            'street_name': 'Queens Boulevard',
            'lat': 40.7265,
            'lng': -73.8614,
            'walkability': 78,
            'food_score': 7,
            'nightlife_score': 4,
            'transit_score': 8,
            'parks_score': 6,
            'diversity_score': 8,
            'safety_score': 8,
            'primary_demographic': 'families',
            'vibe': 'middle-class and commercial',
            'food_density': 'High',
            'sentiment': 7.6
        },
        {
            'name': 'Kew Gardens',
            'admin_area': 'Queens',
            'locality': 'New York',
            'sublocality': 'Kew Gardens',
            'street_name': 'Lefferts Boulevard',
            'lat': 40.7145,
            'lng': -73.8308,
            'walkability': 76,
            'food_score': 7,
            'nightlife_score': 4,
            'transit_score': 7,
            'parks_score': 8,
            'diversity_score': 8,
            'safety_score': 8,
            'primary_demographic': 'families',
            'vibe': 'quiet and green',
            'food_density': 'Medium',
            'sentiment': 7.8
        },
        {
            'name': 'Bayside',
            'admin_area': 'Queens',
            'locality': 'New York',
            'sublocality': 'Bayside',
            'street_name': 'Bell Boulevard',
            'lat': 40.7682,
            'lng': -73.7701,
            'walkability': 70,
            'food_score': 7,
            'nightlife_score': 5,
            'transit_score': 6,
            'parks_score': 8,
            'diversity_score': 8,
            'safety_score': 9,
            'primary_demographic': 'families',
            'vibe': 'suburban and safe',
            'food_density': 'Medium',
            'sentiment': 8.0
        },
        {
            'name': 'Ridgewood',
            'admin_area': 'Queens',
            'locality': 'New York',
            'sublocality': 'Ridgewood',
            'street_name': 'Myrtle Avenue',
            'lat': 40.7022,
            'lng': -73.9053,
            'walkability': 82,
            'food_score': 8,
            'nightlife_score': 7,
            'transit_score': 7,
            'parks_score': 5,
            'diversity_score': 9,
            'safety_score': 7,
            'primary_demographic': 'young professionals',
            'vibe': 'affordable and artsy',
            'food_density': 'High',
            'sentiment': 7.9
        },
        {
            'name': 'Corona',
            'admin_area': 'Queens',
            'locality': 'New York',
            'sublocality': 'Corona',
            'street_name': 'Roosevelt Avenue',
            'lat': 40.7470,
            'lng': -73.8625,
            'walkability': 78,
            'food_score': 8,
            'nightlife_score': 5,
            'transit_score': 7,
            'parks_score': 7,
            'diversity_score': 10,
            'safety_score': 6,
            'primary_demographic': 'families',
            'vibe': 'vibrant Latino community',
            'food_density': 'High',
            'sentiment': 7.5
        },

        # ==================== BRONX ====================
        {
            'name': 'Riverdale',
            'admin_area': 'Bronx',
            'locality': 'New York',
            'sublocality': 'Riverdale',
            'street_name': 'Riverdale Avenue',
            'lat': 40.8908,
            'lng': -73.9057,
            'walkability': 65,
            'food_score': 6,
            'nightlife_score': 3,
            'transit_score': 6,
            'parks_score': 9,
            'diversity_score': 7,
            'safety_score': 9,
            'primary_demographic': 'families',
            'vibe': 'suburban and quiet',
            'food_density': 'Medium',
            'sentiment': 8.1
        },
        {
            'name': 'Fordham',
            'admin_area': 'Bronx',
            'locality': 'New York',
            'sublocality': 'Fordham',
            'street_name': 'Fordham Road',
            'lat': 40.8623,
            'lng': -73.8989,
            'walkability': 80,
            'food_score': 7,
            'nightlife_score': 5,
            'transit_score': 8,
            'parks_score': 5,
            'diversity_score': 9,
            'safety_score': 6,
            'primary_demographic': 'students',
            'vibe': 'college town feel',
            'food_density': 'High',
            'sentiment': 7.3
        },
        {
            'name': 'Belmont',
            'admin_area': 'Bronx',
            'locality': 'New York',
            'sublocality': 'Belmont',
            'street_name': 'Arthur Avenue',
            'lat': 40.8542,
            'lng': -73.8874,
            'walkability': 82,
            'food_score': 10,
            'nightlife_score': 5,
            'transit_score': 7,
            'parks_score': 6,
            'diversity_score': 8,
            'safety_score': 7,
            'primary_demographic': 'families',
            'vibe': 'authentic Italian',
            'food_density': 'Very High',
            'sentiment': 8.1
        },
        {
            'name': 'Mott Haven',
            'admin_area': 'Bronx',
            'locality': 'New York',
            'sublocality': 'Mott Haven',
            'street_name': '3rd Avenue',
            'lat': 40.8088,
            'lng': -73.9203,
            'walkability': 77,
            'food_score': 6,
            'nightlife_score': 5,
            'transit_score': 8,
            'parks_score': 5,
            'diversity_score': 9,
            'safety_score': 5,
            'primary_demographic': 'mixed',
            'vibe': 'emerging arts district',
            'food_density': 'Medium',
            'sentiment': 6.9
        },
        {
            'name': 'Pelham Bay',
            'admin_area': 'Bronx',
            'locality': 'New York',
            'sublocality': 'Pelham Bay',
            'street_name': 'Westchester Avenue',
            'lat': 40.8468,
            'lng': -73.8289,
            'walkability': 68,
            'food_score': 6,
            'nightlife_score': 4,
            'transit_score': 6,
            'parks_score': 10,
            'diversity_score': 8,
            'safety_score': 7,
            'primary_demographic': 'families',
            'vibe': 'quiet with large park',
            'food_density': 'Medium',
            'sentiment': 7.5
        },
        {
            'name': 'City Island',
            'admin_area': 'Bronx',
            'locality': 'New York',
            'sublocality': 'City Island',
            'street_name': 'City Island Avenue',
            'lat': 40.8467,
            'lng': -73.7864,
            'walkability': 75,
            'food_score': 7,
            'nightlife_score': 4,
            'transit_score': 3,
            'parks_score': 9,
            'diversity_score': 6,
            'safety_score': 8,
            'primary_demographic': 'families',
            'vibe': 'nautical small-town',
            'food_density': 'Medium',
            'sentiment': 8.0
        },
        {
            'name': 'Kingsbridge',
            'admin_area': 'Bronx',
            'locality': 'New York',
            'sublocality': 'Kingsbridge',
            'street_name': 'Kingsbridge Road',
            'lat': 40.8782,
            'lng': -73.9041,
            'walkability': 79,
            'food_score': 7,
            'nightlife_score': 5,
            'transit_score': 7,
            'parks_score': 6,
            'diversity_score': 9,
            'safety_score': 6,
            'primary_demographic': 'families',
            'vibe': 'residential and diverse',
            'food_density': 'High',
            'sentiment': 7.4
        },
        {
            'name': 'Soundview',
            'admin_area': 'Bronx',
            'locality': 'New York',
            'sublocality': 'Soundview',
            'street_name': 'Westchester Avenue',
            'lat': 40.8204,
            'lng': -73.8654,
            'walkability': 74,
            'food_score': 6,
            'nightlife_score': 4,
            'transit_score': 7,
            'parks_score': 6,
            'diversity_score': 9,
            'safety_score': 5,
            'primary_demographic': 'families',
            'vibe': 'working-class community',
            'food_density': 'Medium',
            'sentiment': 6.8
        },

        # ==================== STATEN ISLAND ====================
        {
            'name': 'St. George',
            'admin_area': 'Staten Island',
            'locality': 'New York',
            'sublocality': 'St. George',
            'street_name': 'Bay Street',
            'lat': 40.6437,
            'lng': -74.0773,
            'walkability': 70,
            'food_score': 6,
            'nightlife_score': 4,
            'transit_score': 7,
            'parks_score': 8,
            'diversity_score': 7,
            'safety_score': 7,
            'primary_demographic': 'families',
            'vibe': 'waterfront community',
            'food_density': 'Medium',
            'sentiment': 7.5
        },
        {
            'name': 'Stapleton',
            'admin_area': 'Staten Island',
            'locality': 'New York',
            'sublocality': 'Stapleton',
            'street_name': 'Van Duzer Street',
            'lat': 40.6262,
            'lng': -74.0776,
            'walkability': 72,
            'food_score': 6,
            'nightlife_score': 4,
            'transit_score': 6,
            'parks_score': 7,
            'diversity_score': 8,
            'safety_score': 6,
            'primary_demographic': 'families',
            'vibe': 'diverse and historic',
            'food_density': 'Medium',
            'sentiment': 7.2
        },
        {
            'name': 'Tottenville',
            'admin_area': 'Staten Island',
            'locality': 'New York',
            'sublocality': 'Tottenville',
            'street_name': 'Main Street',
            'lat': 40.5073,
            'lng': -74.2403,
            'walkability': 55,
            'food_score': 5,
            'nightlife_score': 3,
            'transit_score': 4,
            'parks_score': 8,
            'diversity_score': 6,
            'safety_score': 9,
            'primary_demographic': 'families',
            'vibe': 'small-town suburban',
            'food_density': 'Low',
            'sentiment': 7.6
        },
        {
            'name': 'Great Kills',
            'admin_area': 'Staten Island',
            'locality': 'New York',
            'sublocality': 'Great Kills',
            'street_name': 'Amboy Road',
            'lat': 40.5548,
            'lng': -74.1507,
            'walkability': 60,
            'food_score': 6,
            'nightlife_score': 3,
            'transit_score': 5,
            'parks_score': 9,
            'diversity_score': 6,
            'safety_score': 8,
            'primary_demographic': 'families',
            'vibe': 'beachside suburban',
            'food_density': 'Medium',
            'sentiment': 7.7
        },
        {
            'name': 'New Dorp',
            'admin_area': 'Staten Island',
            'locality': 'New York',
            'sublocality': 'New Dorp',
            'street_name': 'Hylan Boulevard',
            'lat': 40.5731,
            'lng': -74.1179,
            'walkability': 62,
            'food_score': 6,
            'nightlife_score': 3,
            'transit_score': 5,
            'parks_score': 7,
            'diversity_score': 7,
            'safety_score': 8,
            'primary_demographic': 'families',
            'vibe': 'middle-class residential',
            'food_density': 'Medium',
            'sentiment': 7.4
        },
    ]

    return neighborhoods